name: application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^2.0.4
  flutter_switch: ^0.3.2
  smooth_page_indicator: ^1.0.0+2
  bip39: ^1.0.6
  qr_code_scanner: ^1.0.0
  pointycastle: ^3.6.2
  stream_channel: ^2.1.0
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.2
  eip55: ^1.0.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/profiles_screen/
    - assets/images/social/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
